# Generated by Django 2.0.3 on 2018-03-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
